"""Build DOTformat as a PyInstaller executable.

The spec file is generated fresh on every build instead of relying on a
checked-in ``DOTformat.spec`` (the project's .gitignore now excludes
``*.spec``, since PyInstaller specs are build machine/OS/onefile-choice
specific). This keeps the spec always in sync with the current platform and
with the onefile/onedir choice made in setup.py, and lets us verify it was
written correctly before invoking PyInstaller against it.
"""
from __future__ import annotations
import argparse
import subprocess
import sys
from pathlib import Path

SPEC_TEMPLATE = '''# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by src/utils/build_pyinstaller.py -- do not edit by hand.
# Re-run setup.py to regenerate this file for your platform/onefile choice.
import os
from PyInstaller.utils.hooks import collect_all

ONEFILE = {onefile!r}

base_dir = {base_dir!r}
src_dir = os.path.join(base_dir, 'src')

# Curated import names to try collecting. Only those actually installed will
# contribute resources; failures are silently ignored to keep the build robust.
candidate_libs = [
    'ffmpeg',              # from ffmpeg-python
    'PIL',                 # pillow
    'PyPDF2',
    'pdf2docx',
    'pdf2image',
    'fitz',                # PyMuPDF
    'qrcode',
    'pydub',
    'speech_recognition',
    'img2pdf',
    'pikepdf',
    # SVG support in the image converter. Both are single self-contained native
    # extension modules; they are imported lazily inside functions in
    # src/models/svg_converter.py, so collect them explicitly rather than relying
    # on the import graph reaching them.
    'vtracer',             # raster -> SVG
    'resvg_py',            # SVG -> raster
    'rembg',               # optional - may be absent
    # rembg's own alpha-matting dependency. collect_all('rembg') only copies rembg's
    # own dist-info metadata, not its dependencies' — pymatting reads its version via
    # `importlib.metadata.version(__name__)` at import time, so without this it fails
    # frozen with "PackageNotFoundError: No package metadata was found for pymatting"
    # (even though the pymatting *code* itself gets pulled in fine as a rembg dependency).
    'pymatting',
]

datas = []
binaries = []
hiddenimports = []

for lib in candidate_libs:
    try:
        collected = collect_all(lib)
        datas += collected[0]
        binaries += collected[1]
        hiddenimports += collected[2]
    except Exception:
        # Library not installed or failed to collect; skip.
        pass

# Project-specific data: GUI image and feature scripts.
if os.path.exists(os.path.join(src_dir, 'images', 'image.png')):
    datas.append((os.path.join(src_dir, 'images', 'image.png'), 'images'))

if os.path.exists(os.path.join(src_dir, 'models')):
    datas.append((os.path.join(src_dir, 'models'), 'models'))

# Bundle FFmpeg binaries if a project-local copy is present. Executable names
# differ by OS (ffmpeg vs ffmpeg.exe); this spec is regenerated per-OS anyway,
# so os.name at generation time matches the machine it will run PyInstaller on.
ffmpeg_bin_dir = os.path.join(base_dir, 'ffmpeg', 'bin')
ffmpeg_tool_names = ['ffmpeg.exe', 'ffprobe.exe', 'ffplay.exe'] if os.name == 'nt' else ['ffmpeg', 'ffprobe', 'ffplay']
for tool in ffmpeg_tool_names:
    tool_path = os.path.join(ffmpeg_bin_dir, tool)
    if os.path.exists(tool_path):
        datas.append((tool_path, os.path.join('ffmpeg', 'bin')))

a = Analysis(
    [os.path.join(base_dir, 'main.py')],
    pathex=[base_dir],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure, cipher=None)

icon_path = os.path.join(src_dir, 'images', 'image.ico')
icon = icon_path if os.name == 'nt' and os.path.exists(icon_path) else None

if ONEFILE:
    # Single-file build: everything (interpreter, libs, data) packed into one executable.
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.zipfiles,
        a.datas,
        [],
        name='DOTformat',
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        console=False,
        icon=icon,
    )
else:
    # One-folder build: a thin launcher exe plus a dist/DOTformat/ folder of
    # dependencies. Slower single-file startup is avoided at the cost of a
    # multi-file distribution.
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name='DOTformat',
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        console=False,
        icon=icon,
    )
    coll = COLLECT(
        exe,
        a.binaries,
        a.zipfiles,
        a.datas,
        strip=False,
        upx=True,
        name='DOTformat',
    )
'''


def _venv_python(venv_path: Path) -> Path:
    """Resolve the venv's python executable, falling back to the current
    interpreter when no such venv exists (e.g. CI runners, which already
    isolate dependencies per job without setup.py's own .venv)."""
    candidate = venv_path / "Scripts" / "python.exe" if sys.platform == "win32" else venv_path / "bin" / "python"
    return candidate if candidate.exists() else Path(sys.executable)


def _write_spec(project_root: Path, onefile: bool) -> Path:
    spec_path = project_root / "DOTformat.spec"
    content = SPEC_TEMPLATE.format(onefile=onefile, base_dir=str(project_root))
    spec_path.write_text(content, encoding="utf-8")
    return spec_path


def _verify_spec(spec_path: Path) -> None:
    """Sanity-check the freshly written spec before handing it to PyInstaller.

    Catches truncated writes or an empty template render early, with a clear
    error, instead of letting PyInstaller fail deep inside its own parsing.
    """
    if not spec_path.exists():
        raise RuntimeError(f"Spec file was not created: {spec_path}")
    text = spec_path.read_text(encoding="utf-8")
    if "Analysis(" not in text or "EXE(" not in text:
        raise RuntimeError(f"Generated spec file looks incomplete: {spec_path}")
    compile(text, str(spec_path), "exec")


def build_pyinstaller(project_root: Path, venv_path: Path | None, onefile: bool) -> Path:
    """Generate a fresh DOTformat.spec, verify it, then build with PyInstaller.

    ``venv_path`` may be ``None`` (e.g. when called outside setup.py's own
    virtualenv flow, such as from CI) to always use the current interpreter.

    Returns the path to the produced build: the executable file itself when
    onefile=True (``DOTformat.exe`` on Windows, ``DOTformat`` on Linux), or
    the onedir folder (``dist/DOTformat/``) when onefile=False.
    """
    project_root = Path(project_root)
    spec_path = _write_spec(project_root, onefile)
    _verify_spec(spec_path)

    python_executable = _venv_python(venv_path) if venv_path is not None else Path(sys.executable)
    print(f"Building executable from generated spec ({'onefile' if onefile else 'onedir'})...")
    try:
        subprocess.check_call(
            [str(python_executable), "-m", "PyInstaller", "--noconfirm", str(spec_path)],
            cwd=project_root,
        )
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Error building executable: {e}") from e

    dist_path = project_root / "dist" / "DOTformat"
    if onefile:
        dist_path = dist_path.with_suffix(".exe") if sys.platform == "win32" else dist_path
    print(f"Executable built successfully at {dist_path}!")
    return dist_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Build DOTformat with PyInstaller.")
    parser.add_argument("--project-root", default=Path(__file__).resolve().parents[2], type=Path)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--onefile", action="store_true", help="Build a single-file executable.")
    mode.add_argument("--onedir", action="store_true", help="Build a one-folder distribution.")
    args = parser.parse_args()
    build_pyinstaller(args.project_root, venv_path=None, onefile=args.onefile)


if __name__ == "__main__":
    main()


__all__ = ["build_pyinstaller"]
